---
title: "Survival"
output: html_document
date: "2023-09-04"
author: Santiago López Begines
github: 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
#Libraries
library(readxl)
library(tidyverse)
library(psych)
library(DescTools)
library(car)
library(stats)
library(broom)
library(dunn.test)
library(stats)
library(ggpubr)
library(RcmdrMisc)
library(spatstat.utils)
```


#1. Load data

```{r}
data<- read_excel("Survival_plain_text.xlsx")
```

#2. Cleaning data

```{r}
data$Age_m <- round(data$Age_m, 0)
data$Group <- factor(data$Group, levels=c("NTC","WT","L115","L116"))

#Remove animals with more than 25months and less than 2
data <- data[data$Age_m>=1 & data$Age_m<=30,]
```

```{r}
mean_sem_data <- data %>% 
  filter(Type_of_dead == "MN") %>% 
  group_by(Gender, Group) %>% 
  summarise(mean=mean(Age_m,na.rm = TRUE),
            SD=sd(Age_m,na.rm = TRUE),
            SEM=SD/sqrt(n()),
            N=n(),
            MinAge=min(Age_m),
            MaxAge=max(Age_m))
mean_sem_data
```


# Mixed Data

```{r}
mn<-data %>% 
  filter(Type_of_dead=="MN")

p<- ggplot(mn, aes(x = Age_m, color = Group)) +
  stat_ecdf(geom = "step", size=1.5) +
  scale_color_manual(values = c(NTC = "#808080",
                               WT = "#000000",
                               L115 = "#E42320",
                               L116 = "#2A4B9A")) +
  labs(title = "Cumulative Distribution Comparison",
       x = "Age in Months",
       y = "Cumulative Probability") +
  theme_minimal()+
  theme(axis.line.x.bottom = element_line(color = "black", size = 0.5),
                  axis.line.y.left = element_line(color = "black", size = 0.5))
print(p)
# Create a directory to save the plots (if it doesn't exist)
if (!file.exists("plots")) {
  dir.create("plots")
}
# File path to save the plot
  file_path <- paste0("plots/Survival_Mixed_boxplot.pdf")
  
  # Save the plot in vector format (PDF)
  ggsave(filename = file_path, plot = p, device = "pdf", width = 8, height = 6, units = "in")

```

```{r}
# Load the ks package if not already loaded
library(ks)

mn<-data %>% 
  filter(Type_of_dead=="MN")
# Create an empty matrix to store the p-values
p_values_matrix <- matrix(NA, nrow = 4, ncol = 4)

# Get unique group names
unique_groups <- unique(mn$Group)

# Loop through all possible pairwise combinations of groups
for (i in 1:(length(unique_groups) - 1)) {
  for (j in (i + 1):length(unique_groups)) {
    group_1 <- unique_groups[i]
    group_2 <- unique_groups[j]
    # Subset the data for the two groups being compared
    #data_group1 <- MN_data[MN_data$Group == group1, "cum"]
    #data_group2 <- MN_data[MN_data$Group == group2, "cum"]
    data_group_1 <- mn %>% filter(Group==group_1) %>% pull(Age_m)
    data_group_2 <- mn %>% filter(Group==group_2) %>% pull(Age_m)
    # Perform the KS test
    ks_result <- ks.test(data_group_1, data_group_2)
    
    # Store the p-value in the matrix
    p_values_matrix[i, j] <- ks_result$p.value
    p_values_matrix[j, i] <- ks_result$p.value
  }
}

# Add row and column names to the p-values matrix
rownames(p_values_matrix) <- unique_groups
colnames(p_values_matrix) <- unique_groups
p_val <- as.data.frame(p_values_matrix)
# View the p-values matrix (optional)
print(p_val)
```
```{r}
mn<-data %>% 
  filter(Type_of_dead=="MN"& Group %in% c("WT","L115"))

p<- ggplot(mn, aes(x = Age_m, color = Group)) +
  stat_ecdf(geom = "step", size=1.5) +
  scale_color_manual(values = c(NTC = "#808080",
                               WT = "#000000",
                               L115 = "#E42320",
                               L116 = "#2A4B9A")) +
  labs(title = "Cumulative Distribution Comparison",
       x = "Age in Months",
       y = "Cumulative Probability") +
  theme_minimal()+
  theme(axis.line.x.bottom = element_line(color = "black", size = 0.5),
                  axis.line.y.left = element_line(color = "black", size = 0.5))
print(p)
# File path to save the plot
  file_path <- paste0("plots/Survival_Mixed_boxplot_WT_L115.pdf")
  
  # Save the plot in vector format (PDF)
  ggsave(filename = file_path, plot = p, device = "pdf", width = 8, height = 6, units = "in")
```
# Females


```{r}
mn<-data %>% 
  filter(Type_of_dead=="MN" & Gender =="Female")

p<- ggplot(mn, aes(x = Age_m, color = Group)) +
  stat_ecdf(geom = "step", size=1.5) +
  scale_color_manual(values = c(NTC = "#808080",
                               WT = "#000000",
                               L115 = "#E42320",
                               L116 = "#2A4B9A")) +
  labs(title = "Cumulative Distribution Comparison",
       x = "Age in Months",
       y = "Cumulative Probability") +
  theme_minimal()+theme(axis.line.x.bottom = element_line(color = "black", size = 0.5),
                  axis.line.y.left = element_line(color = "black", size = 0.5))
print(p)
# Create a directory to save the plots (if it doesn't exist)
if (!file.exists("plots")) {
  dir.create("plots")
}
# File path to save the plot
  file_path <- paste0("plots/Survival_Females_boxplot.pdf")
  
  # Save the plot in vector format (PDF)
  ggsave(filename = file_path, plot = p, device = "pdf", width = 8, height = 6, units = "in")

```

```{r}
# Load the ks package if not already loaded
library(ks)

mn<-data %>% 
  filter(Type_of_dead=="MN"& Gender =="Female")
# Create an empty matrix to store the p-values
p_values_matrix <- matrix(NA, nrow = 4, ncol = 4)

# Get unique group names
unique_groups <- unique(mn$Group)

# Loop through all possible pairwise combinations of groups
for (i in 1:(length(unique_groups) - 1)) {
  for (j in (i + 1):length(unique_groups)) {
    group_1 <- unique_groups[i]
    group_2 <- unique_groups[j]
    # Subset the data for the two groups being compared
    #data_group1 <- MN_data[MN_data$Group == group1, "cum"]
    #data_group2 <- MN_data[MN_data$Group == group2, "cum"]
    data_group_1 <- mn %>% filter(Group==group_1) %>% pull(Age_m)
    data_group_2 <- mn %>% filter(Group==group_2) %>% pull(Age_m)
    # Perform the KS test
    ks_result <- ks.test(data_group_1, data_group_2)
    
    # Store the p-value in the matrix
    p_values_matrix[i, j] <- ks_result$p.value
    p_values_matrix[j, i] <- ks_result$p.value
  }
}

# Add row and column names to the p-values matrix
rownames(p_values_matrix) <- unique_groups
colnames(p_values_matrix) <- unique_groups
p_val_female<- as.data.frame(p_values_matrix)
# View the p-values matrix (optional)
print(p_val_female)
```
# Males


```{r}
mn<-data %>% 
  filter(Type_of_dead=="MN" & Gender =="Male")

p<- ggplot(mn, aes(x = Age_m, color = Group)) +
  stat_ecdf(geom = "step", size=1.5) +
  scale_color_manual(values = c(NTC = "#808080",
                               WT = "#000000",
                               L115 = "#E42320",
                               L116 = "#2A4B9A")) +
  labs(title = "Cumulative Distribution Comparison",
       x = "Age in Months",
       y = "Cumulative Probability") +
  theme_minimal()+
  theme(axis.line.x.bottom = element_line(color = "black", size = 0.5),
                  axis.line.y.left = element_line(color = "black", size = 0.5))
print(p)
# Create a directory to save the plots (if it doesn't exist)
if (!file.exists("plots")) {
  dir.create("plots")
}
# File path to save the plot
  file_path <- paste0("plots/Survival_Males_boxplot.pdf")
  
  # Save the plot in vector format (PDF)
  ggsave(filename = file_path, plot = p, device = "pdf", width = 8, height = 6, units = "in")

```


```{r}
# Load the ks package if not already loaded
library(ks)

mn<-data %>% 
  filter(Type_of_dead=="MN"& Gender =="Male")
# Create an empty matrix to store the p-values
p_values_matrix <- matrix(NA, nrow = 4, ncol = 4)

# Get unique group names
unique_groups <- unique(mn$Group)

# Loop through all possible pairwise combinations of groups
for (i in 1:(length(unique_groups) - 1)) {
  for (j in (i + 1):length(unique_groups)) {
    group_1 <- unique_groups[i]
    group_2 <- unique_groups[j]
    # Subset the data for the two groups being compared
    #data_group1 <- MN_data[MN_data$Group == group1, "cum"]
    #data_group2 <- MN_data[MN_data$Group == group2, "cum"]
    data_group_1 <- mn %>% filter(Group==group_1) %>% pull(Age_m)
    data_group_2 <- mn %>% filter(Group==group_2) %>% pull(Age_m)
    # Perform the KS test
    ks_result <- ks.test(data_group_1, data_group_2)
    
    # Store the p-value in the matrix
    p_values_matrix[i, j] <- ks_result$p.value
    p_values_matrix[j, i] <- ks_result$p.value
  }
}

# Add row and column names to the p-values matrix
rownames(p_values_matrix) <- unique_groups
colnames(p_values_matrix) <- unique_groups
p_val_male <- as.data.frame(p_values_matrix)
# View the p-values matrix (optional)
print(p_val_male)
```

```{r}
mn<-data %>% 
  filter(Type_of_dead=="MN" & Gender =="Male" & Group %in% c("WT","L115","L116"))

p<- ggplot(mn, aes(x = Age_m, color = Group)) +
  stat_ecdf(geom = "step") +
  scale_color_manual(values = c(NTC = "#808080",
                               WT = "#000000",
                               L115 = "#E42320",
                               L116 = "#2A4B9A")) +
  labs(title = "Cumulative Distribution Comparison",
       x = "Age in Months",
       y = "Cumulative Probability") +
  theme_minimal()
print(p)
# Create a directory to save the plots (if it doesn't exist)
if (!file.exists("plots")) {
  dir.create("plots")
}
# File path to save the plot
  file_path <- paste0("plots/Survival_Males_boxplot_WT_L115.pdf")
  
  # Save the plot in vector format (PDF)
  ggsave(filename = file_path, plot = p, device = "pdf", width = 8, height = 6, units = "in")

```
# Tables
```{r}
# Load required libraries
library(kableExtra)
dataframes <- c("p_val","p_val_female","p_val_male", "mean_sem_data")

for (i in 1:length(dataframes)) {
  df <- get(dataframes[i])
  cols <- colnames(df)  # Get the column names of the dataframe
  p <- knitr::kable(df, "html") %>% 
    kableExtra::kable_paper("striped", full_width = F, font_size = 14) 
  #%>%     add_header_above(header = list(cols))  # Use a list to specify the header row
  print(dataframes[i])
  print(p)
}

```


# Export resulst as CSV
```{r}

# Carga la librería openxlsx
library(openxlsx)

# Crea un nuevo libro de Excel
wb <- createWorkbook()

# Agrega cada dataframe como una hoja en el libro
for (df_name in dataframes) {
  df <- get(df_name)  # Get the dataframe by its name
  addWorksheet(wb, sheetName = df_name)
  writeData(wb, sheet = df_name, x = df)
}

# Guarda el libro de Excel
saveWorkbook(wb, file = "dataframes.xlsx", overwrite = TRUE)
```




## Not included


```{r}
MN_data <- data %>% 
  filter(Type_of_dead=="MN") %>% 
  group_by(Group, Age_m) %>% 
  summarise(N = n())
MN_data
```


```{r}
MN_data$prop <- MN_data %>% 
  group_by(Group) %>% 
  summarise(prop=N/sum(N),
            cumprop=cumsum(prop))

MN_data$cum <- MN_data$prop$cumprop
MN_data$prop <- MN_data$prop$prop

```

```{r}
ggplot(MN_data) +
  aes(x = Age_m, y = cum, fill = Group) +
  geom_col(position="dodge") +
  geom_line()+
  scale_fill_hue(direction = 1) +
    scale_fill_manual(values = c(NTC = "#808080",
                               WT = "#D4D3D3",
                               L115 = "#E42320",
                               L116 = "#2A4B9A")) +
  theme_minimal() 
```
